### ISSUE TITLE
哈哈哈哈哈哈哈哈哈哈哈哈首頁文案超爆笑

### ISSUE THREAD

**Issue by Caldis** [ComicsReader/comicsreader.github.io#1]
純吐槽一下, 我自己關掉這單 XD

**Comment by Yukaii** [comment]
😆

**Comment by Caldis** [comment]
其實我最近也在看 Electron, 於是也寫了個漫畫閱讀器來練手, 然後就搜索到這個, 發現其實社區裡面這類軟體真挺多的, 只是在社區外面出名的好像就不多了

PS: 不知道為什麼看漫畫的 Developer 們總喜歡做這類 APP (我也一樣 XD), 可能就跟寫文的 Developer 總喜歡自己折騰博客網站一樣
